services:
  api:
    depends_on:
      - redis
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    command: npm run start:dev
    ports:
      - 3000:3000
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
volumes:
  redis:
    driver: local
