version: "2"

services:
  api:
    depends_on:
      - redis
      - postgres
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    command: npm run start:dev
    ports:
      - 3000:3000
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  redis:
    driver: local
  db:
    driver: local
